source 'https://rubygems.org'

gem 'sass'
gem 'jekyll'
gem 'nokogiri'
gem 'redcarpet', '~> 2.3'
gem 'albino', '~> 1.3'
gem 'font-awesome-sass'
gem 'jekyll-paginate'
gem 'jekyll-paginate-category'
gem 'jekyll-sitemap'
